version: 2.1

jobs:
  build:
    docker:
      - image: selenium/standalone-chrome
      - image: adoptopenjdk/maven-openjdk11
    steps:
      - checkout
      - run: java --version
      - run: mvn --version
      - run: mvn test -DsuiteXmlFile=smokeTest.xml


