version: 2.1

jobs:
  build:
    docker:
      - image: selenium/standalone-chrome
      - image: cimg/openjdk:11.0.0
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn clean test


