version: 2.1

jobs:
  build:
    docker:
      - image: selenium/standalone-chrome
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn test -DsuiteXmlFile=smokeTest.xml


