version: 2.1
orbs:
  maven: circleci/maven@1.4.1
jobs:
  build:
    docker:
      - image: selenium/standalone-chrome
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: java --version
      - run: mvn --version
      - run: mvn clean test -DsuiteXmlFile=smokeTest.xml


