version: 2.1

jobs:
  build:
    docker:
      - image: selenium/standalone-chrome
      - image: cimg/openjdk:11.0
      - image: cimg/maven@0.0.12
    steps:
      - checkout
      - run: java --version
      - run: mvn --version
      - run: mvn clean test -DsuiteXmlFile=smokeTest.xml


