version: 2.1

orbs:
  maven: circleci/maven@0.0.12
jobs:
  build:
    docker:
      - image: selenium/standalone-chrome
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: echo "This is Hybdrid Framework Env"
      - run: mvn clean test -DsuiteXmlFile=smokeTest.xml


