version: 2.1

jobs:
  build:
    docker:
      - image: selenium/standalone-chrome
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn test


