version: 2.1

jobs:
  build:
    docker:
      - image: selenium/standalone-chrome

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn test


