version: 2.1
executors:
  java11-executor:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  build:
    executor: java11-executor
    steps:
      - checkout  # Check out the code from the repository
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Build and Test
          command: mvn clean verify
