version: 2.1

orbs:
  maven: circleci/maven@0.0.12
jobs:
  build:
    docker:
      - image: selenium/standalone-chrome
    steps:
      - checkout
      - run: echo "This is Hybdrid Framework Env"

workflows:
  build_and_test:
    jobs:
      - build
      - test: mvn clean test -DsuiteXmlFile=smokeTest.xml
          requires:
            - build
