version: 2.1
executors:
  java11-executor:
    docker:
      - image: cimg/openjdk:11.0.0
      - image: selenium/standalone-chrome
jobs:
  build:
    executor: java11-executor
    steps:
      - checkout  # Check out the code from the repository
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Build and Test
          command: mvn test -DsuiteXmlFile=smokeTest.xml
      - run: 
          name: Checking File
          command: ls 
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/art-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts

        